apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pinger-b
  namespace: ping-app
spec:
  serviceName: "pinger-b-service"
  replicas: 2
  selector:
    matchLabels:
      app: pinger-b
  template:
    metadata:
      labels:
        app: pinger-b
    spec:
      automountServiceAccountToken: false
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pinger-a
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: pinger-b
        image: matteoclz/pinger-b:latest # Placeholder
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TARGET_APP
          value: "pinger-a"
        - name: TARGET_SERVICE
          value: "pinger-a-service"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: pinger-b-service
  namespace: ping-app
spec:
  clusterIP: None
  selector:
    app: pinger-b