name: Build and Push Docker Images

on:
  push:
    branches:
      - main # Trigger il workflow ad ogni push sul branch 'main'

jobs:
  build-pinger-a:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push pinger-a image
        uses: docker/build-push-action@v5
        with:
          context: ./app/pinger-a
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pinger-a:latest

  build-pinger-b:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push pinger-b image
        uses: docker/build-push-action@v5
        with:
          context: ./app/pinger-b
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pinger-b:latest

  deploy-to-machine-a:
    runs-on: [self-hosted, kind-machine-a] # Esegui su un runner self-hosted con l'etichetta 'kind-machine-a'
    needs: [build-pinger-a, build-pinger-b] # Dipende dai job di build e push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Apply Kubernetes manifests for app on Machine A
        run: kubectl apply -f k8s/app/
