apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner-sa
  namespace: github-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-runner-clusterrole
rules:
- apiGroups: ["", "apps"]
  resources: ["statefulsets", "services", "namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-runner-clusterrole-binding
subjects:
- kind: ServiceAccount
  name: github-runner-sa
  namespace: github-runner
roleRef:
  kind: ClusterRole
  name: github-runner-clusterrole
  apiGroup: rbac.authorization.k8s.io