apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner-deployment
  namespace: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      serviceAccountName: github-runner-sa
      containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        env:
        - name: RUNNER_NAME
          value: "kind-runner-machine-a"
        - name: RUNNER_WORKDIR
          value: "/_work"
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-secret
              key: runner-token
        - name: GITHUB_URL
          value: "https://github.com/matteocolazilli/asdn-pinging-project"
        - name: RUNNER_LABELS
          value: "kind-machine-a"
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: runner-data
          mountPath: /_work
        command: ["/bin/bash"]
        args:
          - "-c"
          - >
            ./config.sh --url $GITHUB_URL
            --token $RUNNER_TOKEN
            --name $RUNNER_NAME
            --labels $RUNNER_LABELS
            --work $RUNNER_WORKDIR
            --unattended
            --replace &&
            ./run.sh
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: runner-data
        emptyDir: {}
